import * as v from 'valibot';

// ============================================================================
// BAG SCHEMAS
// ============================================================================

/**
 * Bag Schema - SINGLE SOURCE OF TRUTH
 *
 * A bag is a free-form dose that is not stored in a freezer tube.
 */
export const bagSchema = v.object({
	id: v.pipe(v.string(), v.uuid()),
	weight: v.pipe(v.number('Weight must be a number'), v.minValue(1, 'Weight must be >= 1g')),
	creationDate: v.string(),
	coffeeId: v.number()
});

/**
 * Bag Creation Schema
 *
 * Used for creating new bags.
 * The id and creationDate are auto-generated by the database.
 */
export const bagCreationSchema = v.pick(bagSchema, ['weight', 'coffeeId']);

/**
 * Bag Deletion Schema
 *
 * Used for identifying which bag to delete.
 * Only includes the id.
 */
export const bagDeletionSchema = v.pick(bagSchema, ['id']);
