import * as v from 'valibot';

// ============================================================================
// FREE FORM DOSE SCHEMAS
// ============================================================================

/**
 * Free Form Dose Schema - SINGLE SOURCE OF TRUTH
 *
 * This schema defines the domain model for a free form dose entity.
 * Free form doses are doses not stored in the physical drawer system.
 */
export const freeFormDoseSchema = v.object({
	id: v.pipe(v.string(), v.uuid()),
	weight: v.pipe(v.number(), v.minValue(0)),
	creationDate: v.string(),
	coffeeId: v.number()
});

/**
 * Free Form Dose Creation Schema
 *
 * Used for creating new free form doses.
 * The id and creationDate are auto-generated by the database.
 */
export const freeFormDoseCreationSchema = v.pick(freeFormDoseSchema, ['weight', 'coffeeId']);

/**
 * Free Form Dose Deletion Schema
 *
 * Used for identifying which free form dose to delete.
 * Only includes the id.
 */
export const freeFormDoseDeletionSchema = v.pick(freeFormDoseSchema, ['id']);
